name: test-workflow
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build project
        run: mvn -B package

      - name: Upload project jar
        uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: target/*.jar

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download project jar
        uses: actions/download-atifact@v2
        with:
          name: app.jar
          path: target/app.jar

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: canaparro/git-actions-test:latest